packages:
  - "apps/*"
  - "packages/*"
overrides:
  postcss: ^8.5.10
  qs: ^6.15.2
  tmp: ^0.2.6
allowBuilds:
  '@sentry/cli': false
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  tesseract.js: true
  unrs-resolver: true
