-- §9.8 / issue #455 — conversations.active_persona_id FK (deferred).
--
-- The conversations.active_persona_id column exists (added in
-- 20260521150000_conversations_messages.sql) but the personas table does NOT
-- exist yet. Personas are slug-keyed code-side structures (see BP10); the
-- persona_switch route currently stores null in active_persona_id and reads
-- the slug from [persona_switch] system messages instead.
--
-- The FK (REFERENCES public.personas(id) ON DELETE SET NULL) will be added
-- when the personas table ships. Until then this migration is intentionally
-- empty to hold the timestamp slot.
--
-- Re-open: issue #455.
