-- Migration: ai_batch_purpose_add_rescreen
-- Version:   20260722000002
-- Generated by scripts/new-migration.sh
-- Branch:    feature/sweep-ai-batch2-1695
--
-- #1695 — widen the purpose CHECK on both ai_batch_jobs and
-- ai_batch_requests to include 'persona_addendum_rescreen'.
--
-- The original 20260528000001_ai_batches.sql CHECK listed only five of the
-- six BatchablePurpose union members (apps/main/src/lib/ai/batch/types.ts),
-- omitting persona_addendum_rescreen. That purpose is live: the nightly
-- rescreen producer (persona-addendum-rescreen-nightly.ts) enqueues rows with
-- it and aiBatchFlushPersonaAddendumRescreen flushes them hourly — so every
-- enqueue hit a 23514 CHECK violation and the pipeline was broken end-to-end.
--
-- The inline CHECKs from the CREATE TABLE were auto-named <table>_purpose_check
-- by Postgres. Drop-and-recreate (rather than a new differently-named
-- constraint) keeps the schema clean and idempotent. No policy or grant
-- changes, so no RLS/grants snapshot regen is required.

ALTER TABLE public.ai_batch_jobs
  DROP CONSTRAINT IF EXISTS ai_batch_jobs_purpose_check;
ALTER TABLE public.ai_batch_jobs
  ADD CONSTRAINT ai_batch_jobs_purpose_check CHECK (purpose IN (
    'precruise_generation',
    'memory_extraction',
    'persona_addendum_screen',
    'persona_addendum_rescreen',
    'rag_pii_redaction',
    'rag_normalization'
  ));

ALTER TABLE public.ai_batch_requests
  DROP CONSTRAINT IF EXISTS ai_batch_requests_purpose_check;
ALTER TABLE public.ai_batch_requests
  ADD CONSTRAINT ai_batch_requests_purpose_check CHECK (purpose IN (
    'precruise_generation',
    'memory_extraction',
    'persona_addendum_screen',
    'persona_addendum_rescreen',
    'rag_pii_redaction',
    'rag_normalization'
  ));
