-- Migration: ai_batch_requests_anthropic_batch_id
-- Version:   20260722000005
-- Generated by scripts/new-migration.sh
-- Branch:    feature/sweep-ai-batch2-1695
--
-- #1696 — adopt stranded claimed rows when a crash lands between a successful
-- Anthropic submit and the ai_batch_jobs insert/link.
--
-- Add a nullable anthropic_batch_id to ai_batch_requests. flush.ts stamps it
-- (together with submitted_at) immediately after submitAnthropicBatch returns,
-- BEFORE inserting the ai_batch_jobs row. If the process then dies before the
-- job insert/link, the row still records which live Anthropic batch it belongs
-- to — so the adoption sweep (reconcile) can create/find the ai_batch_jobs row
-- and link it, instead of orphaning a paid-for batch or resubmitting it (which
-- would double-spend, D-091 #21).
--
-- Partial index backs the sweep's exact predicate: still-claimed rows that
-- carry a batch id but were never linked to a job. It stays tiny — only the
-- stranded rows in the crash window ever match, and adoption empties it.
-- No policy/grant change (table-level GRANT already covers new columns), so
-- no RLS/grants snapshot regen is required.

ALTER TABLE public.ai_batch_requests
  ADD COLUMN IF NOT EXISTS anthropic_batch_id TEXT;

CREATE INDEX IF NOT EXISTS ai_batch_requests_stranded_idx
  ON public.ai_batch_requests (submitted_at)
  WHERE status = 'submitted'
    AND batch_job_id IS NULL
    AND anthropic_batch_id IS NOT NULL;

COMMENT ON COLUMN public.ai_batch_requests.anthropic_batch_id IS
  'The Anthropic batch id this row was submitted under, stamped right after submit success and before the ai_batch_jobs link. Lets the reconcile adoption sweep recover rows stranded by a crash in that window (#1696).';
